/* eslint-disable */
import * as Router from 'expo-router';

export * from 'expo-router';

declare module 'expo-router' {
  export namespace ExpoRouter {
    export interface __routes<T extends string | object = string> {
      hrefInputParams: { pathname: Router.RelativePathString, params?: Router.UnknownInputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownInputParams } | { pathname: `/../src/components/SafeAreaContainer`; params?: Router.UnknownInputParams; } | { pathname: `/../src/assets/colors/theme`; params?: Router.UnknownInputParams; } | { pathname: `/../src/assets/api/client`; params?: Router.UnknownInputParams; } | { pathname: `/../src/assets/types/userDataType`; params?: Router.UnknownInputParams; } | { pathname: `/../src/assets/utils/responsive`; params?: Router.UnknownInputParams; } | { pathname: `/../src/screens/Auth/Login/LoginScreen`; params?: Router.UnknownInputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownInputParams; };
      hrefOutputParams: { pathname: Router.RelativePathString, params?: Router.UnknownOutputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownOutputParams } | { pathname: `/../src/components/SafeAreaContainer`; params?: Router.UnknownOutputParams; } | { pathname: `/../src/assets/colors/theme`; params?: Router.UnknownOutputParams; } | { pathname: `/../src/assets/api/client`; params?: Router.UnknownOutputParams; } | { pathname: `/../src/assets/types/userDataType`; params?: Router.UnknownOutputParams; } | { pathname: `/../src/assets/utils/responsive`; params?: Router.UnknownOutputParams; } | { pathname: `/../src/screens/Auth/Login/LoginScreen`; params?: Router.UnknownOutputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownOutputParams; };
      href: Router.RelativePathString | Router.ExternalPathString | `/../src/components/SafeAreaContainer${`?${string}` | `#${string}` | ''}` | `/../src/assets/colors/theme${`?${string}` | `#${string}` | ''}` | `/../src/assets/api/client${`?${string}` | `#${string}` | ''}` | `/../src/assets/types/userDataType${`?${string}` | `#${string}` | ''}` | `/../src/assets/utils/responsive${`?${string}` | `#${string}` | ''}` | `/../src/screens/Auth/Login/LoginScreen${`?${string}` | `#${string}` | ''}` | `/_sitemap${`?${string}` | `#${string}` | ''}` | { pathname: Router.RelativePathString, params?: Router.UnknownInputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownInputParams } | { pathname: `/../src/components/SafeAreaContainer`; params?: Router.UnknownInputParams; } | { pathname: `/../src/assets/colors/theme`; params?: Router.UnknownInputParams; } | { pathname: `/../src/assets/api/client`; params?: Router.UnknownInputParams; } | { pathname: `/../src/assets/types/userDataType`; params?: Router.UnknownInputParams; } | { pathname: `/../src/assets/utils/responsive`; params?: Router.UnknownInputParams; } | { pathname: `/../src/screens/Auth/Login/LoginScreen`; params?: Router.UnknownInputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownInputParams; };
    }
  }
}
